export const proyects = [
  {
    id: 1,
    title: 'PROYECTO',
    link: 'https://colegio.vercel.app/',
    text: 'Proyecto de grado de secundaria de una alternativa de solución para mejorar la calidad evaluativa online del docente de 5to A, En el Colegio María Santísima (React js - Firebase js - Chakra ui)', 
    url: 'public/assets/img/proyects/colegio.png', 
    alt: 'colegio'
  },
  {
    id: 2,
    title: 'ANIMALIA',
    link: 'https://proyect-psi.vercel.app/',
    text: 'Sitio web para prensentar las mejores imagenes con su mejor calidad (Next js - Chakra ui)', 
    url: 'public/assets/img/proyects/animale.png', 
    alt: 'animales',
  },
  {
    id: 3,
    title: 'CARTAS MARIO BROS',
    link: 'https://rohyllerp.github.io/cartas/',
    text: 'Sitio web para juego de cartas con tiempo y mejor tiempo incluido (Javascript - Boostrap - Css y Html)', 
    url: 'public/assets/img/proyects/cartas.png',
    alt: 'cartas',
  },
  {
    id: 4,
    title: 'Almacen',
    link: 'http://gestor.myartsonline.com/',
    text: 'Mini sitio web con LOGIN, y vista para productos (PHP - MYSQL - Javascript - Boostrap - CSS y Html)', 
    url: 'public/assets/img/proyects/almacen.png',
    alt: 'Almacen',
  },
  {
    id: 5,
    title: 'NOTAS',
    link: 'https://rohyllerp.github.io/notas/',
    text: 'Sitio web de un ejemplo de "to-do list" donde podemos crear categorias y en esas categorias crear tareas, editar tareas, eliminar tareas y más. Todas estas se guardarán a pesar que cierres la ventana. (HTML - BOOSTRAP - JQUERY)', 
    url: 'public/assets/img/proyects/notas.png',
    alt: 'notas',
  },
  {
    id: 6,
    title: 'CALCULADORA',
    link: 'https://rohyllerp.github.io/calculadora/',
    text: 'Sitio web responsive de ejemplo de una calculadora funcional, tiene además cambio de color en modo oscuro y modo claro. (HTML,CSS,JAVASCRIPT)', 
    url: 'public/assets/img/proyects/calculadora.png',
    alt: 'calculadora',
  },
];
